branch-defaults:
  default:
    environment: StoreREST2-dev
  master:
    environment: StoreREST2-dev
global:
  application_name: StoreREST2
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  sc: git
